set_sleep_timer:
  name: Set sleep timer
  description: Pause playback after set time.
  target:
    device:
      integration: mqtt_sonos
    entity:
      integration: mqtt_sonos
      domain: media_player
  fields:
    sleep_time:
      name: Sleep Time
      description: How long should we wait before sleeping
      required: true
      selector:
        duration:

clear_sleep_timer:
  name: Clear sleep timer
  description: Cancel the sleep timer
  target:
    device:
      integration: mqtt_sonos
    entity:
      integration: mqtt_sonos
      domain: media_player

snooze:
  name: Snooze alarm
  description: Snooze the currently running alarm
  target:
    device:
      integration: mqtt_sonos
    entity:
      integration: mqtt_sonos
      domain: media_player
  fields:
    snooze_time:
      name: Snooze time
      description: How long do you want to snooze
      required: true
      selector:
        duration:

clear_snooze:
  name: Cancel snoozed alarm
  description: Cancel a previously snoozed alarm
  target:
    entity:
      integration: mqtt_sonos
      domain: media_player

group_volume:
  name: Set group volume
  description: Change volume for all players in the group
  target:
    entity:
      integration: mqtt_sonos
      domain: media_player
  fields:
    volume_level:
      name: Level
      description: Volume level to set as float.
      required: true
      selector:
        number:
          min: 0
          max: 1
          step: 0.01

group_volume_up:
  name: Turn up group volume
  description: Turn a media player volume up.
  target:
    entity:
      integration: mqtt_sonos
      domain: media_player

group_volume_down:
  name: Turn down group volume
  description: Turn a media player volume down.
  target:
    entity:
      integration: mqtt_sonos
      domain: media_player
