set_sleep_timer:
  name: Set sleep timer
  description: Pause playback after set time.
  target:
    device:
      integration: mqtt_sonos
    entity:
      integration: mqtt_sonos
      domain: media_player
  fields:
    sleep_time:
      name: Sleep Time
      description: How long should we wait before sleeping
      required: true
      selector:
        duration:

clear_sleep_timer:
  name: Clear sleep timer
  description: Cancel the sleep timer
  target:
    device:
      integration: mqtt_sonos
    entity:
      integration: mqtt_sonos
      domain: media_player

snooze:
  name: Snooze alarm
  description: Snooze the currently running alarm
  target:
    device:
      integration: mqtt_sonos
    entity:
      integration: mqtt_sonos
      domain: media_player
  fields:
    snooze_time:
      name: Snooze time
      description: How long do you want to snooze
      required: true
      selector:
        duration:
